name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  jest-react:
    runs-on: ubuntu-latest
    steps:
      # 下载代码
      - uses: actions/checkout@v3

      # 下载 node
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          
      # 下载 pnpm
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2

      # 运行 jest 单元测试
      - name: Run jest
        run: |
          pnpm install
          pnpm run test
