name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  jest-react:
    runs-on: ubuntu-latest
    steps:
      # 下载代码
      - uses: actions/checkout@v3
      # 运行 jest 单元测试
      - name: Run jest
        run: |
          pnpm install
          pnpm run test
